services:
  php:
    image: ghcr.io/open-telemetry/opentelemetry-php/opentelemetry-php-base:${PHP_VERSION:-8.2}
    volumes:
    - ./:/usr/src/myapp
    user: "${PHP_USER}:root"
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG:-''}
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG:-''}
      GITHUB_TOKEN: ${GITHUB_TOKEN:-''}
